anki:
    collection: ""
    deck: ""
    note_type: ""
    word_field: ""
    sentence_field: ""
    image_field: ""
    audio_field: ""
    meaning_field: ""
    words_file: ""
    failed_words_file: ""
